#!/usr/bin/env node
// embed_timings.js
// Reads Timings/truth.txt (or Timings/base.txt) as raw binary and generates
// a Lua module that returns the data as a hex-escaped string literal.
// At runtime, the existing Deserializer can decode this embedded data.

const fs = require("fs");
const path = require("path");

const candidates = ["Timings/truth.txt", "Timings/base.txt"];
const outputPath = path.join("Game", "Timings", "InternalTimingData.lua");

let sourceFile = null;
let raw = null;

for (const candidate of candidates) {
    const full = path.resolve(candidate);
    if (fs.existsSync(full)) {
        raw = fs.readFileSync(full);
        sourceFile = candidate;
        break;
    }
}

if (!raw || raw.length === 0) {
    // No timing file found — generate empty module so the bundle still compiles
    console.log("[embed_timings] No timing file found, generating empty module.");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, 'return ""\n', "utf-8");
    process.exit(0);
}

// Convert binary data to base64 — pure ASCII, no escape sequences,
// avoids Luau compiler recursion on \xNN sequences.
const b64 = raw.toString("base64");

// Build the Lua module: single string literal in a long bracket to avoid any escaping.
// Includes a minimal base64 decoder since Roblox doesn't have a native one.
const luaSource = `-- Auto-generated by embed_timings.js. Do not edit.
-- Source: ${sourceFile} (${raw.length} bytes)
local b64 = [=[${b64}]=]
local function decode_b64(data)
    local b = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    local result = {}
    data = data:gsub("[^" .. b .. "=]", "")
    for i = 1, #data, 4 do
        local a, b2, c, d =
            b:find(data:sub(i, i), 1, true) or 0,
            b:find(data:sub(i + 1, i + 1), 1, true) or 0,
            b:find(data:sub(i + 2, i + 2), 1, true) or 0,
            b:find(data:sub(i + 3, i + 3), 1, true) or 0
        a, b2, c, d = (a or 1) - 1, (b2 or 1) - 1, (c or 1) - 1, (d or 1) - 1
        local n = a * 262144 + b2 * 4096 + c * 64 + d
        local c1 = string.char(math.floor(n / 65536) % 256)
        local c2 = string.char(math.floor(n / 256) % 256)
        local c3 = string.char(n % 256)
        table.insert(result, c1)
        if data:sub(i + 2, i + 2) ~= "=" then table.insert(result, c2) end
        if data:sub(i + 3, i + 3) ~= "=" then table.insert(result, c3) end
    end
    return table.concat(result)
end
return decode_b64(b64)
`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, luaSource, "utf-8");
console.log(
    `[embed_timings] Embedded ${raw.length} bytes from ${sourceFile} into ${outputPath}`
);
