#!/usr/bin/env node
// embed_timings.js
// Reads Timings/truth.txt (or Timings/base.txt) as raw binary and generates
// a Lua module that returns the data as a hex-escaped string literal.
// At runtime, the existing Deserializer can decode this embedded data.

const fs = require("fs");
const path = require("path");

const candidates = ["Timings/truth.txt", "Timings/base.txt"];
const outputPath = path.join("Game", "Timings", "InternalTimingData.lua");

let sourceFile = null;
let raw = null;

for (const candidate of candidates) {
    const full = path.resolve(candidate);
    if (fs.existsSync(full)) {
        raw = fs.readFileSync(full);
        sourceFile = candidate;
        break;
    }
}

if (!raw || raw.length === 0) {
    // No timing file found — generate empty module so the bundle still compiles
    console.log("[embed_timings] No timing file found, generating empty module.");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, 'return ""\n', "utf-8");
    process.exit(0);
}

// Convert binary data to a Lua hex-escaped string: "\xAB\xCD..."
// Split into chunks to avoid extremely long lines
const CHUNK_SIZE = 256;
const parts = [];
for (let i = 0; i < raw.length; i += CHUNK_SIZE) {
    const slice = raw.subarray(i, Math.min(i + CHUNK_SIZE, raw.length));
    let escaped = "";
    for (const byte of slice) {
        escaped += "\\x" + byte.toString(16).padStart(2, "0");
    }
    parts.push('"' + escaped + '"');
}

// Build the Lua module: concatenate all chunk strings
const luaSource =
    "-- Auto-generated by embed_timings.js. Do not edit.\n" +
    "-- Source: " + sourceFile + " (" + raw.length + " bytes)\n" +
    "return " + parts.join("\n.. ") + "\n";

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, luaSource, "utf-8");
console.log(
    `[embed_timings] Embedded ${raw.length} bytes from ${sourceFile} into ${outputPath}`
);
